packages:
  - 'p31-delta-hiring'
  - 'bonding'
  - 'k4-personal'
  - 'p31ca'
  - 'spaceship-earth'
  - 'workers'
  - 'packages/*'
  - 'extensions/*'
  - '../../packages/ui-facets'

onlyBuiltDependencies:
  - '@react-three/fiber'
  - three
