name = "p31-kofi-webhook"
main = "p31_kofi_webhook_worker.js"
compatibility_date = "2025-04-01"

[vars]
# Non-secret config

[[kv_namespaces]]
binding = "NODE_COUNT_KV"
id = "b719a74443e147c1a72aaa3232625168"
