CREATE TABLE IF NOT EXISTS clients(id SERIAL PRIMARY KEY, nm TEXT NOT NULL, addr TEXT NOT NULL, est_min INTEGER DEFAULT 120);
CREATE TABLE IF NOT EXISTS jobs(id SERIAL PRIMARY KEY, cid INTEGER NOT NULL, stat TEXT DEFAULT 'act', start_ts INTEGER NOT NULL, end_ts INTEGER, FOREIGN KEY(cid) REFERENCES clients(id));
CREATE TABLE IF NOT EXISTS sync_queue(id SERIAL PRIMARY KEY, pl TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_jobs_stat ON jobs(stat);
CREATE INDEX IF NOT EXISTS idx_jobs_cid ON jobs(cid);
