import type { NotificationPayload } from "../types";

interface EmailEnv {
  DB: D1Database;
  MAILCHANNELS_API: string;
}

export async function sendEmail(
  env: EmailEnv,
  payload: NotificationPayload,
): Promise<boolean> {
  try {
    const resp = await fetch(env.MAILCHANNELS_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        personalizations: [{ to: [{ email: payload.to }] }],
        from: {
          email: "cortex@p31ca.org",
          name: "P31 Cortex",
        },
        subject: payload.subject,
        content: [
          {
            type: "text/plain",
            value: payload.body,
          },
        ],
      }),
    });

    if (!resp.ok) {
      console.error(`Mailchannels error: ${resp.status} ${await resp.text()}`);
      return false;
    }

    // Log notification
    await env.DB.prepare(
      "INSERT INTO notifications_log (id, to_addr, subject, body, priority, status) VALUES (?, ?, ?, ?, ?, ?)",
    )
      .bind(
        crypto.randomUUID(),
        payload.to,
        payload.subject,
        payload.body,
        payload.priority,
        "sent",
      )
      .run();

    return true;
  } catch (err) {
    console.error("Email send failed:", err);
    return false;
  }
}

export function formatDeadlineAlert(
  title: string,
  dueDate: string,
  daysRemaining: number,
  category: string,
): NotificationPayload {
  const urgency =
    daysRemaining <= 1
      ? "⚠️ DUE TOMORROW"
      : daysRemaining <= 3
        ? "🔶 DUE IN " + daysRemaining + " DAYS"
        : "📋 " + daysRemaining + " DAYS REMAINING";

  return {
    to: "", // set by caller
    subject: `${urgency}: ${title}`,
    body: [
      `P31 CORTEX — DEADLINE ALERT`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `Category: ${category.toUpperCase()}`,
      `Title: ${title}`,
      `Due: ${dueDate}`,
      `Days remaining: ${daysRemaining}`,
      ``,
      `This alert was generated by P31 Cortex.`,
      `It's okay to be a little wonky. 🔺`,
    ].join("\n"),
    priority:
      daysRemaining <= 1 ? "high" : daysRemaining <= 3 ? "high" : "normal",
  };
}
