name = "phos-api"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "if (-not (Test-Path dist)) { New-Item -ItemType Directory -Path dist }; Copy-Item src/worker.ts dist/_worker.js"

[vars]

[[kv_namespaces]]
binding = "PHOS_STATE"
id = "4ba5783f48f54caaa226c94a7f1c2c5f"
preview_id = "4ba5783f48f54caaa226c94a7f1c2c5f"

[[kv_namespaces]]
binding = "PHOS_CACHE"
id = "5530628220d74314bad9867ccd8fece4"
preview_id = "5530628220d74314bad9867ccd8fece4"

[[d1_databases]]
binding = "PHOS_EVENT_LOG"
database_name = "phos-event-log"
database_id = "1554838e-6f6e-48fa-80cf-1ab1f2fab549"

[[services]]
binding = "PHOS_ATMOSPHERE"
service = "phos-atmosphere"

[[durable_objects.bindings]]
name = "WS_HUB"
class_name = "WebSocketHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHub"]

[env.production]
routes = ["phos.p31ca.org/api/*"]

[env.preview]
routes = ["phos.preview.p31ca.org/api/*"]
