// P31 Gridiron Dynamic Momentum System — Canonical v2.0.0
// Spoons generated by success, depleted by failure
// Based on real football momentum - big plays energize, turnovers drain
// UI updated to canonical colors and Unicode indicators

import { useState, useEffect, ReactNode } from 'react';
import type { SpoonState, SpoonAllocation } from '../types';

// ============================================
// CANONICAL SPOON COLORS (from p31-universal-canon.json)
// ============================================

const SPOON_COLORS = {
  high: '#5DCAA5',    // teal
  medium: '#cda852',  // amber
  low: '#cc6247',     // coral
} as const;

// Canonical Unicode indicators (no emoji)
const SPOON_ICONS = {
  loading: '◐',
  inactive: '○',
  active: '●',
} as const;

// ============================================
// MOMENTUM STATE CONTEXT (Outcome-Based Spoons)
// ============================================

import { createContext, useContext } from 'react';

interface SpoonContextType {
  spoonState: SpoonState;
  setSpoonState: (state: SpoonState) => void;
  spoonsRemaining: number;
  useSpoons: (amount: number) => boolean;
  addSpoons: (amount: number, reason: string) => void;
  allocation: SpoonAllocation | null;
  lastPlayResult: string | null;
  streak: number; // consecutive successful plays
}

const SpoonContext = createContext<SpoonContextType>({
  spoonState: 6,
  setSpoonState: () => {},
  spoonsRemaining: 20, // start with 20 spoons
  useSpoons: () => false,
  addSpoons: () => {},
  allocation: null,
  lastPlayResult: null,
  streak: 0,
});

export function SpoonProvider({ children }: { children: ReactNode }) {
  const [spoonState, setSpoonState] = useState<SpoonState>(6);
  const [allocation, setAllocation] = useState<SpoonAllocation | null>(null);
  const [spoonsRemaining, setSpoonsRemaining] = useState(20); // start with 20 spoons
  const [lastPlayResult, setLastPlayResult] = useState<string | null>(null);
  const [streak, setStreak] = useState(0);

  // Initialize from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('p31-gridiron-momentum');
    if (saved) {
      const parsed = JSON.parse(saved);
      setSpoonsRemaining(parsed.spoons || 20);
      setStreak(parsed.streak || 0);
    }
  }, []);

  // Persist changes
  useEffect(() => {
    localStorage.setItem('p31-gridiron-momentum', JSON.stringify({
      spoons: spoonsRemaining,
      streak,
      lastUpdate: Date.now()
    }));
  }, [spoonsRemaining, streak]);

  // Passive recovery - 1 spoon every 30 seconds (encourages taking breaks)
  useEffect(() => {
    const interval = setInterval(() => {
      setSpoonsRemaining(prev => Math.min(prev + 1, 50)); // cap at 50
    }, 30000);
    return () => clearInterval(interval);
  }, []);

  // Use spoons for a play
  const useSpoons = (amount: number): boolean => {
    if (spoonsRemaining < amount) {
      // Allow the play but show warning - don't block gameplay
      return true;
    }

    setSpoonsRemaining(prev => Math.max(0, prev - amount));
    return true;
  };

  // Add spoons based on play outcome
  const addSpoons = (amount: number, reason: string) => {
    setSpoonsRemaining(prev => {
      const newValue = Math.min(prev + amount, 50); // cap at 50
      console.log(`[Momentum] +${amount} spoons: ${reason} (total: ${newValue})`);
      return newValue;
    });
    setLastPlayResult(reason);

    if (amount > 0) {
      setStreak(s => s + 1);
    } else if (amount < 0) {
      setStreak(0); // reset streak on negative plays
    }
  };

  return (
    <SpoonContext.Provider value={{
      spoonState,
      setSpoonState,
      spoonsRemaining,
      useSpoons,
      addSpoons,
      allocation,
      lastPlayResult,
      streak
    }}>
      {children}
    </SpoonContext.Provider>
  );
}

export function useSpoons() {
  return useContext(SpoonContext);
}

// ============================================
// MOMENTUM CALCULATOR (Based on Play Outcome)
// ============================================

export function calculateMomentumGain(outcome: {
  yards: number;
  touchdown?: boolean;
  firstDown?: boolean;
  turnover?: boolean;
  turnoverType?: string;
}): { spoons: number; message: string } {
  // Big plays generate spoons (momentum)
  if (outcome.touchdown) {
    return { spoons: 8, message: 'TOUCHDOWN! +8 spoons' };
  }

  if (outcome.turnover) {
    if (outcome.turnoverType === 'INTERCEPTION') {
      return { spoons: -5, message: 'Interception... -5 spoons' };
    }
    if (outcome.turnoverType === 'FUMBLE') {
      return { spoons: -4, message: 'Fumble! -4 spoons' };
    }
    return { spoons: -3, message: 'Turnover -3 spoons' };
  }

  if (outcome.firstDown) {
    return { spoons: 3, message: 'First Down! +3 spoons' };
  }

  if (outcome.yards >= 15) {
    return { spoons: 4, message: `Big Play! +${outcome.yards} yards +4 spoons` };
  }

  if (outcome.yards >= 10) {
    return { spoons: 2, message: `Solid gain +${outcome.yards} yards +2 spoons` };
  }

  if (outcome.yards >= 5) {
    return { spoons: 1, message: `+${outcome.yards} yards +1 spoon` };
  }

  if (outcome.yards > 0) {
    return { spoons: 0, message: `+${outcome.yards} yards` };
  }

  if (outcome.yards === 0) {
    return { spoons: 0, message: 'No gain' };
  }

  // Negative yards (loss)
  return { spoons: -1, message: `Loss of ${Math.abs(outcome.yards)} yards -1 spoon` };
}

// ============================================
// SPOON SELECTOR (App Entry)
// ============================================

interface SpoonSelectorProps {
  onSelect: (state: SpoonState) => void;
}

export function SpoonSelector({ onSelect }: SpoonSelectorProps) {
  const [hovered, setHovered] = useState<SpoonState | null>(null);

  const options: Array<{ state: SpoonState; label: string; time: string; desc: string; color: string; footballTerm: string }> = [
    {
      state: 1,
      label: 'Coordinators Only',
      time: '5 min',
      desc: 'Gameplan selection only. Let AI handle play-calling. Big plays still earn spoons.',
      color: SPOON_COLORS.high,
      footballTerm: 'Auto-Coach'
    },
    {
      state: 3,
      label: 'Assistant Coach',
      time: '15 min',
      desc: 'Swipe-based play calling. Momentum system: touchdowns +8, first downs +3.',
      color: SPOON_COLORS.medium,
      footballTerm: 'Rhythm Offense'
    },
    {
      state: 6,
      label: 'Head Coach',
      time: '30 min',
      desc: 'Full playbook. Dynamic spoon economy based on play outcomes.',
      color: SPOON_COLORS.low,
      footballTerm: 'Game Manager'
    },
  ];

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '100vh',
      background: 'var(--p31-void, #0f1115)',
      color: 'var(--p31-cloud, #d8d6d0)',
      padding: '2rem',
      fontFamily: 'Atkinson Hyperlegible, sans-serif',
    }}>
      <div style={{ fontSize: '3rem', marginBottom: '0.5rem' }}>{SPOON_ICONS.active}</div>
      <h1 style={{ fontSize: '2.5rem', marginBottom: '0.5rem', fontWeight: 300 }}>
        P31 Gridiron
      </h1>
      <p style={{ fontSize: '1rem', opacity: 0.7, marginBottom: '3rem' }}>
        American Football Management Simulation
      </p>

      <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap', justifyContent: 'center' }}>
        {options.map((option) => (
          <button
            key={option.state}
            onClick={() => onSelect(option.state)}
            onMouseEnter={() => setHovered(option.state)}
            onMouseLeave={() => setHovered(null)}
            style={{
              width: '280px',
              padding: '2rem',
              border: `2px solid ${hovered === option.state ? option.color : 'transparent'}`,
              borderRadius: '12px',
              background: hovered === option.state ? 'rgba(255,255,255,0.05)' : 'rgba(255,255,255,0.02)',
              cursor: 'pointer',
              transition: 'all 0.15s ease',
              textAlign: 'left',
              color: 'inherit',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
              {/* Canonical Unicode indicator */}
              <span style={{ fontSize: '1.25rem', color: option.color }}>{SPOON_ICONS.active}</span>
              <span style={{ fontSize: '1.25rem', fontWeight: 'bold', color: option.color }}>
                {option.footballTerm}
              </span>
            </div>

            <h3 style={{ fontSize: '1.5rem', margin: '0 0 0.5rem 0', color: option.color, fontWeight: 600 }}>
              {option.label}
            </h3>
            <p style={{ fontSize: '0.875rem', opacity: 0.6, margin: '0 0 0.5rem 0', fontFamily: 'JetBrains Mono, monospace' }}>
              {option.footballTerm} • {option.time}
            </p>
            <p style={{ fontSize: '0.875rem', opacity: 0.8, lineHeight: 1.5 }}>
              {option.desc}
            </p>
          </button>
        ))}
      </div>

      <p style={{ marginTop: '3rem', fontSize: '0.75rem', opacity: 0.4, maxWidth: '400px', textAlign: 'center' }}>
        Based on Spoon Theory. Choose the mode matching your cognitive capacity.
        You can always adjust later.
      </p>
    </div>
  );
}

// ============================================
// SPOON STATUS INDICATOR (Canonical)
// ============================================

export function SpoonStatus() {
  const { spoonsRemaining, spoonState, streak } = useSpoons();
  const [showTooltip, setShowTooltip] = useState(false);

  const percentage = Math.min((spoonsRemaining / 50) * 100, 100);

  // Canonical color logic
  const getColor = () => {
    if (percentage > 50) return SPOON_COLORS.high;
    if (percentage > 25) return SPOON_COLORS.medium;
    return SPOON_COLORS.low;
  };

  const color = getColor();

  return (
    <div
      style={{
        position: 'fixed',
        top: '1rem',
        right: '1rem',
        background: 'rgba(22, 25, 32, 0.9)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        borderRadius: '8px',
        padding: '0.75rem 1rem',
        color: '#d8d6d0',
        fontSize: '0.875rem',
        fontFamily: 'JetBrains Mono, monospace',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.25rem',
        zIndex: 1000,
        minWidth: '160px',
        cursor: 'help',
      }}
      onMouseEnter={() => setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
    >
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          {/* Canonical Unicode indicator */}
          <span style={{ color }}>{SPOON_ICONS.active}</span>
          <span style={{ fontWeight: 'bold', color }}>
            {Math.floor(spoonsRemaining)}
          </span>
        </div>
        {/* Streak indicator using Unicode, not emoji */}
        {streak > 2 && (
          <span style={{
            fontSize: '0.75rem',
            color: SPOON_COLORS.medium,
            fontWeight: 'bold',
          }}>
            ×{streak}
          </span>
        )}
      </div>

      {/* Progress bar */}
      <div style={{
        height: '4px',
        background: 'rgba(255,255,255,0.1)',
        borderRadius: '2px',
        overflow: 'hidden'
      }}>
        <div style={{
          height: '100%',
          width: `${percentage}%`,
          background: color,
          transition: 'width 0.25s ease'
        }} />
      </div>

      <div style={{ fontSize: '0.7rem', opacity: 0.6 }}>
        {spoonState === 1 ? 'Auto-Coach Mode' :
         spoonState === 3 ? 'Rhythm Offense' :
         'Full Control'}
      </div>
      <div style={{ fontSize: '0.65rem', opacity: 0.4 }}>
        Good plays +spoons, bad plays -spoons
      </div>

      {/* Tooltip */}
      {showTooltip && (
        <div style={{
          position: 'absolute',
          top: '100%',
          right: 0,
          marginTop: '0.5rem',
          background: 'rgba(22, 25, 32, 0.95)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: '8px',
          padding: '0.75rem 1rem',
          fontSize: '0.75rem',
          minWidth: '180px',
          zIndex: 1001,
        }}>
          <div style={{ marginBottom: '0.25rem' }}>
            Momentum: {Math.round(percentage)}%
          </div>
          {streak > 0 && (
            <div style={{ color: SPOON_COLORS.medium }}>
              Streak: {streak} plays
            </div>
          )}
          <div style={{ opacity: 0.7, marginTop: '0.25rem' }}>
            Recovery: +1 spoon/30s
          </div>
        </div>
      )}
    </div>
  );
}

// ============================================
// ADAPTIVE UI COMPONENTS
// ============================================

interface AdaptiveContainerProps {
  children: ReactNode;
  spoonState: SpoonState;
}

export function AdaptiveContainer({ children, spoonState }: AdaptiveContainerProps) {
  const styles = {
    1: { fontSize: '1.5rem', lineHeight: 1.6, maxWidth: '600px', padding: '2rem' },
    3: { fontSize: '1rem', lineHeight: 1.5, maxWidth: '900px', padding: '1.5rem' },
    6: { fontSize: '0.875rem', lineHeight: 1.4, maxWidth: '1400px', padding: '1rem' },
  };

  return (
    <div style={{ ...styles[spoonState], margin: '0 auto' }}>
      {children}
    </div>
  );
}

// ============================================
// PLAY CALLER UI (Football-specific)
// ============================================

interface PlayCallerProps {
  onCallPlay: (playId: string) => void;
  spoonState: SpoonState;
  down: number;
  distance: number;
  yardLine: number;
}

export function PlayCaller({ onCallPlay, spoonState, down, distance, yardLine }: PlayCallerProps) {
  const isRedZone = yardLine > 80;

  // Simplified play selection for low spoons
  if (spoonState === 1) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <h2 style={{ fontSize: '2rem', marginBottom: '1rem', fontWeight: 600 }}>Auto-Coach Active</h2>
        <p style={{ opacity: 0.6, fontSize: '1.25rem' }}>
          {down === 1 && 'First down - Balanced approach'}
          {down === 2 && 'Second down - Continue the drive'}
          {down === 3 && `Third & ${distance} - ${distance > 5 ? 'Pass situation' : 'Run or pass'}`}
          {down === 4 && (yardLine > 65 ? 'Field goal range' : 'Punt for field position')}
        </p>
        <button
          onClick={() => onCallPlay('AUTO')}
          style={{
            marginTop: '2rem',
            padding: '1.5rem 3rem',
            fontSize: '1.5rem',
            background: SPOON_COLORS.high,
            color: '#0f1115',
            border: 'none',
            borderRadius: '12px',
            cursor: 'pointer',
            fontWeight: 600,
            fontFamily: 'Atkinson Hyperlegible, sans-serif',
          }}
        >
          Execute Play
        </button>
      </div>
    );
  }

  // Medium complexity
  if (spoonState === 3) {
    const categories = [
      { id: 'RUN', label: 'Run', symbol: '▲', color: SPOON_COLORS.high },
      { id: 'PASS', label: 'Pass', symbol: '◆', color: '#8b7cc9' },  // lavender
      { id: 'SPECIAL', label: 'Special', symbol: '★', color: SPOON_COLORS.medium },
    ];

    return (
      <div style={{ padding: '1.5rem' }}>
        <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
          <span style={{ fontSize: '1.5rem', fontWeight: 'bold', fontFamily: 'JetBrains Mono, monospace' }}>
            {down}{down === 1 ? 'st' : down === 2 ? 'nd' : down === 3 ? 'rd' : 'th'} & {distance}
          </span>
          {isRedZone && <span style={{ color: SPOON_COLORS.low, marginLeft: '1rem', fontWeight: 'bold' }}>Red Zone</span>}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
          {categories.map(cat => (
            <button
              key={cat.id}
              onClick={() => onCallPlay(cat.id)}
              style={{
                padding: '2rem',
                fontSize: '1.25rem',
                background: cat.color,
                color: cat.id === 'RUN' ? '#0f1115' : '#d8d6d0',
                border: 'none',
                borderRadius: '12px',
                cursor: 'pointer',
                fontWeight: 600,
                fontFamily: 'Atkinson Hyperlegible, sans-serif',
              }}
            >
              {cat.symbol} {cat.label}
            </button>
          ))}
        </div>
      </div>
    );
  }

  // Full play calling (6 spoons)
  return (
    <div style={{ padding: '1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <div>
          <span style={{ fontSize: '1.25rem', fontWeight: 'bold', fontFamily: 'JetBrains Mono, monospace' }}>
            {down}{down === 1 ? 'st' : down === 2 ? 'nd' : down === 3 ? 'rd' : 'th'} & {distance}
          </span>
          <span style={{ marginLeft: '1rem', opacity: 0.6 }}>Ball on {yardLine > 50 ? `OPP ${100 - yardLine}` : `OWN ${yardLine}`}</span>
        </div>
        {isRedZone && <span style={{ color: SPOON_COLORS.low, fontWeight: 'bold' }}>RED ZONE</span>}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.75rem' }}>
        {['Inside Zone', 'Outside Zone', 'Power O', 'Draw', 'Slants', 'Play Action', 'Screen', 'Four Verts'].map(play => (
          <button
            key={play}
            onClick={() => onCallPlay(play)}
            style={{
              padding: '1rem',
              fontSize: '1rem',
              background: 'rgba(77, 184, 168, 0.15)',
              color: '#d8d6d0',
              border: '1px solid rgba(77, 184, 168, 0.3)',
              borderRadius: '8px',
              cursor: 'pointer',
              textAlign: 'left',
              fontFamily: 'Atkinson Hyperlegible, sans-serif',
              transition: 'all 0.15s ease',
            }}
          >
            {play}
          </button>
        ))}
      </div>
    </div>
  );
}
