CREATE TABLE IF NOT EXISTS clients(id SERIAL PRIMARY KEY, nm TEXT NOT NULL, phone TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS formulas(id SERIAL PRIMARY KEY, cid INTEGER NOT NULL, base TEXT, dev TEXT, tgt TEXT, notes TEXT, ts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sync_queue(id SERIAL PRIMARY KEY, pl TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_formulas_cid ON formulas(cid);
