#!/usr/bin/env bash
# ==============================================================================
# P31 Node Zero — WiFi Credential Provisioner
# Generates an NVS partition binary with WiFi SSID + password,
# then flashes it to the NVS partition without erasing the rest of flash.
#
# Usage:
#   ./provision.sh [--port /dev/ttyUSB0] [--ssid MyNet] [--pass MyPass]
#
# Requires:
#   - ESP-IDF environment activated (. $IDF_PATH/export.sh)
#   - esptool.py on PATH
#   - Python 3 with nvs_partition_gen.py (bundled in ESP-IDF)
# ==============================================================================

set -euo pipefail

G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m' R='\033[0;31m' N='\033[0m'
log()  { echo -e "${G}[provision]${N} $1"; }
warn() { echo -e "${Y}  !${N} $1"; }
err()  { echo -e "${R}  ERR${N} $1"; exit 1; }

# ── Parse args ────────────────────────────────────────────────────────────────
PORT="/dev/ttyUSB0"
SSID=""
PASS=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --port) PORT="$2"; shift 2 ;;
        --ssid) SSID="$2"; shift 2 ;;
        --pass) PASS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# ── Interactive prompts if not provided ───────────────────────────────────────
if [ -z "$SSID" ]; then
    echo -ne "${C}WiFi SSID: ${N}"
    read -r SSID
fi

if [ -z "$PASS" ]; then
    echo -ne "${C}WiFi password (hidden): ${N}"
    read -rs PASS
    echo ""
fi

if [ -z "$SSID" ] || [ -z "$PASS" ]; then
    err "SSID and password are required"
fi

# ── Locate nvs_partition_gen.py ───────────────────────────────────────────────
if [ -z "${IDF_PATH:-}" ]; then
    err "IDF_PATH not set — run: . \$HOME/esp/esp-idf/export.sh"
fi

NVS_GEN="$IDF_PATH/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py"
[ -f "$NVS_GEN" ] || err "nvs_partition_gen.py not found at $NVS_GEN"

# ── Build NVS CSV ─────────────────────────────────────────────────────────────
TMPDIR=$(mktemp -d)
CSV="$TMPDIR/nvs.csv"
BIN="$TMPDIR/nvs.bin"

cat > "$CSV" << EOF
key,type,encoding,value
p31,namespace,,
wifi_ssid,data,string,${SSID}
wifi_pass,data,string,${PASS}
EOF

log "Generating NVS partition binary..."
python3 "$NVS_GEN" generate "$CSV" "$BIN" 0x6000

# ── Flash NVS partition only ──────────────────────────────────────────────────
# NVS is at 0x9000 in our partitions.csv (standard ESP32-S3 layout)
log "Flashing NVS to 0x9000 on $PORT..."
esptool.py --port "$PORT" --baud 921600 write_flash 0x9000 "$BIN"

rm -rf "$TMPDIR"

log "Done — Node Zero will join '${SSID}' on next boot"
echo ""
echo -e "  ${C}DID is generated by firmware on first boot.${N}"
echo -e "  ${C}Monitor serial output to capture it: idf.py -p $PORT monitor${N}"
