name = "spin-logistics"
main = "./dist/index.js"
compatibility_date = "2024-10-22"

durable_objects = { bindings = [{ name = "LOGISTICS", class_name = "HandoverDO" }] }

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["HandoverDO"]
