name = "spin-logistics"
main = "./index.ts"
compatibility_date = "2024-10-22"

[durable_objects]
bindings = [{ name = "LOGISTICS", class_name = "HandoverDO" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HandoverDO"]
