name = "p31-app-hub"
type = "javascript"
account_id = "ee05f70c889cb6f876b9925257e3a2fa"
workers_dev = true
main = "dist/index.mjs"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "app-hub.trimtab-signal.workers.dev", zone_name = "trimtab-signal.workers.dev" }
]

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
