#!/usr/bin/env bash
# P31 eSIM Activation Runbook — EXEC-07 / Gap D
# iPhone 11 (model A2111) — dual SIM: physical nano-SIM + eSIM
#
# This script DOCUMENTS the steps. It cannot activate the eSIM itself
# (that requires iPhone UI interaction). Run each section as a checklist.
#
# Usage: bash esim-runbook.sh [--check] [--carrier US_MOBILE|MINT|TELLO]

CARRIER="${2:-US_MOBILE}"

cat <<'HEADER'
╔═══════════════════════════════════════════════════════════════╗
║     P31 eSIM Activation — EXEC-07 / Gap D                    ║
║     iPhone 11 (A2111) — cellular fallback for sovereignty     ║
╚═══════════════════════════════════════════════════════════════╝
HEADER

echo ""
echo "CARRIER COMPARISON (as of 2026-05):"
echo "┌────────────────┬─────────┬────────────┬───────────┬──────────────────────┐"
echo "│ Carrier        │ Network │ Monthly    │ eSIM      │ 2FA SMS test         │"
echo "├────────────────┼─────────┼────────────┼───────────┼──────────────────────┤"
echo "│ US Mobile Warp │ Verizon │ \$10/mo     │ Instant   │ ✓ (all 2FA services) │"
echo "│ US Mobile GSM  │ T-Mobile│ \$9/mo      │ Instant   │ ✓                   │"
echo "│ Mint Mobile    │ T-Mobile│ \$15/mo     │ 10 min    │ ✓                   │"
echo "│ Tello          │ T-Mobile│ \$8/mo      │ Manual    │ ✓ (slower)          │"
echo "│ Visible        │ Verizon │ \$25/mo     │ Minutes   │ ✓ (party pay avail) │"
echo "└────────────────┴─────────┴────────────┴───────────┴──────────────────────┘"
echo ""
echo "RECOMMENDATION: US Mobile Warp (Verizon network, \$10/mo, instant eSIM, best 911)"
echo ""

echo "══ PHASE 1: Account Setup (desktop) ══════════════════════════════"
echo ""
echo "1.1  Go to: https://www.usmobile.com"
echo "     → Choose: Warp (Verizon) plan"
echo "     → Plan: 1GB data / unlimited talk & text / \$10/mo"
echo "     → Select: eSIM (no physical SIM needed)"
echo ""
echo "1.2  Create account with: will@p31ca.org"
echo "     → Port your number if needed, OR get a new number"
echo "     → For sovereign fallback: NEW number recommended (no port dependency)"
echo ""
echo "1.3  Payment: use Mercury bank card (or Stripe virtual card)"
echo ""
echo "══ PHASE 2: iPhone eSIM Installation ════════════════════════════"
echo ""
echo "2.1  iPhone 11 Settings → Cellular → Add Cellular Plan"
echo "     OR: Settings → Cellular → Add eSIM"
echo ""
echo "2.2  Scan QR code from US Mobile (in account dashboard)"
echo "     → 'Activate' prompt will appear"
echo "     → Provisioning: <5 minutes on Verizon"
echo ""
echo "2.3  After activation:"
echo "     → Settings → Cellular → 'US Mobile' (or carrier name)"
echo "     → Enable: 'Allow this line to make calls' and 'Use for iMessage'"
echo "     → Data mode: use Wi-Fi Calling as primary (preserves sovereignty)"
echo ""
echo "2.4  Label the line: Settings → Cellular → choose line → Label → 'P31 Sovereign'"
echo ""
echo "══ PHASE 3: Verification ════════════════════════════════════════"
echo ""
echo "3.1  Test 2FA SMS from:"
echo "     □ Mercury Bank (text 'verify' to their SMS)"
echo "     □ Cloudflare account settings → phone verification"
echo "     □ Google account (G Suite)"
echo "     □ Stripe dashboard"
echo ""
echo "3.2  Test E911:"
echo "     → Verify: Settings → Emergency SOS → 'Call with Hold and Release'"
echo "     → Confirm the eSIM line is listed under emergency call settings"
echo "     NOTE: Do NOT actually dial 911 to test. Verify via carrier coverage map."
echo ""
echo "3.3  Test Wi-Fi calling (critical — your primary connectivity is Wi-Fi):"
echo "     → Settings → Cellular → US Mobile line → Wi-Fi Calling"
echo "     → Enable and confirm: 'Wi-Fi Calling On This iPhone'"
echo ""
echo "3.4  Log results to P31 audit trail:"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "     echo '{\"event\":\"esim_activation\",\"carrier\":\"US_MOBILE\",\"ts\":\"$TIMESTAMP\",\"status\":\"PENDING\"}' \\"
echo "       >> \$HOME/andromeda/ops/esim-log.json"
echo ""
echo "══ PHASE 4: Sovereign Failover Config ══════════════════════════"
echo ""
echo "4.1  Physical SIM backup:"
echo "     → Keep original physical nano-SIM in safe as cold backup"
echo "     → Label: 'P31 Physical SIM Backup — [carrier] [number]'"
echo ""
echo "4.2  Carrier switching (if eSIM fails):"
echo "     → US Mobile supports eSIM profile swap without deactivation"
echo "     → Go to: usmobile.com/account → 'Manage eSIM'"
echo ""
echo "4.3  Annual cost:"
echo "     US Mobile Warp: \$10/mo = \$120/yr (or \$99/yr prepaid)"
echo "     Mint Mobile:    \$15/mo = \$180/yr (or \$120/yr for 3GB annual plan)"
echo ""
echo "4.4  Add to .env.master:"
echo "     ESIM_CARRIER=US_MOBILE_WARP"
echo "     ESIM_NUMBER=REPLACE_after_activation"
echo "     ESIM_ACCOUNT_EMAIL=will@p31ca.org"
echo ""
echo "══ STATUS ═══════════════════════════════════════════════════════"
echo ""
if [ "${1:-}" = "--check" ]; then
  echo "Checking eSIM status via carrier APIs... (not implemented — check iPhone UI)"
fi
echo "  ⬜ Account created at carrier"
echo "  ⬜ eSIM QR code scanned"
echo "  ⬜ Activation confirmed (<5 min)"
echo "  ⬜ Wi-Fi calling enabled"
echo "  ⬜ 2FA SMS verified (Mercury, Cloudflare, Stripe)"
echo "  ⬜ E911 confirmed in settings"
echo "  ⬜ Physical SIM stored in safe"
echo "  ⬜ Number logged in ops/esim-log.json"
echo ""
echo "When complete, update ops/esim-log.json with final status."
