#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = join(__filename, "..", "..");

function countSurfaces(): number {
  try {
    const content = readFileSync(join(ROOT, "phos/src/surfaces/SurfaceContent.tsx"), "utf-8");
    const matches = content.match(/case\s+'[A-Z_]+'/g);
    return matches ? matches.length : 0;
  } catch { return 0; }
}

const data = {
  generated: new Date().toISOString(),
  metrics: {
    phosSurfaces: countSurfaces(),
    bondingTestCount: 488,
    githubRepos: 7,
  },
};

const output = "// AUTO-GENERATED by scripts/generate-site-data.ts\n// Do not edit manually.\nexport const SITE_DATA = " + JSON.stringify(data, null, 2) + " as const;\n";

const outPath = join(ROOT, "phosphorus31.org/planetary-planet/src/data/site-data.ts");
writeFileSync(outPath, output);
console.log("Generated:", JSON.stringify(data.metrics));
