// Generated by Wrangler by running `wrangler types`

interface Env {
	MATCHMAKING: DurableObjectNamespace /* MatchmakingDO */;
	LOGISTICS: DurableObjectNamespace /* HandoverDO from spin-logistics */;
}
