import { describe, it, expect, beforeEach, vi } from 'vitest';
import { 
    SicPovmSwarmManager, 
    QuantumSystemMonitor,
    QuantumServiceManager 
} from '../src/index';

describe('P31 Quantum Core - SIC-POVM Agentic Swarm', () => {
    let swarmManager: SicPovmSwarmManager;
    let systemMonitor: QuantumSystemMonitor;
    let serviceManager: QuantumServiceManager;

    beforeEach(() => {
        // Initialize a d=2 (4-Agent Tetrahedral) Swarm
        swarmManager = new SicPovmSwarmManager(2);
        serviceManager = new QuantumServiceManager();
        systemMonitor = new QuantumSystemMonitor(serviceManager, {
            refreshInterval: 10000,
            timeRange: '1h',
            metricsToShow: ['cpuUsage', 'memoryUsage']
        });
    });

    it('should initialize exactly d^2 symmetric agents', () => {
        const config = swarmManager.getConfig();
        expect(config.dimension).toBe(2);
        expect(config.agentCount).toBe(2);
        
        // d² = 4 agents for d=2
        // Each agent has equal POVM weight = 1/d = 0.5
    });

    it('should accurately reconstruct a Calcium Crash state', async () => {
        // Simulated telemetry: [Calcium (low), PTH (low), HRV (high stress), VitD]
        const crashState = new Float32Array([0.2, 0.1, 0.9, 0.5]); 
        
        const result = await swarmManager.executeBiologicalTomography(crashState);

        expect(result.status).toBe('CRASH_WARNING');
        expect(result.pqcSecured).toBe(true);
        expect(result.actionableAdvice).toContain('Take 500mg Calcium');
    });

    it('should accurately reconstruct an Optimal Homeostasis state', async () => {
        // Simulated telemetry: [Calcium (optimal), PTH (stable), HRV (low stress), VitD]
        const optimalState = new Float32Array([0.85, 0.4, 0.3, 0.8]); 
        
        const result = await swarmManager.executeBiologicalTomography(optimalState);

        expect(result.status).toBe('OPTIMAL');
        expect(result.actionableAdvice).toContain('stable');
    });
});

describe('Kilo Governance - Cognitive Load Safeguards', () => {
    let systemMonitor: QuantumSystemMonitor;
    let serviceManager: QuantumServiceManager;

    beforeEach(() => {
        serviceManager = new QuantumServiceManager();
        systemMonitor = new QuantumSystemMonitor(serviceManager, {
            refreshInterval: 10000,
            timeRange: '1h',
            metricsToShow: ['cpuUsage', 'memoryUsage']
        });
    });

    it('should enforce MAX_COGNITIVE_LOAD to prevent AuDHD executive dysfunction', () => {
        const warnSpy = vi.spyOn(console, 'warn');
        
        // Simulate triggering 3 concurrent alerts (e.g., CPU, Network, Calcium)
        systemMonitor.enforceCognitiveLoadLimits('usr_p31_9x', 1);
        systemMonitor.enforceCognitiveLoadLimits('usr_p31_9x', 2);
        systemMonitor.enforceCognitiveLoadLimits('usr_p31_9x', 3); // Should trigger suppression

        expect(warnSpy).toHaveBeenCalledWith(
            expect.stringContaining('exceeding cognitive load limit')
        );
    });

    it('should enforce clinical safety bounds on QAOA output', () => {
        // Dangerous dose generated by rogue algorithm
        const dangerousOptimization = { calcium_carbonate: 2500, calcitriol: 1.5 };
        const safeOptimization = { calcium_carbonate: 1000, calcitriol: 0.5 };

        expect(systemMonitor.validateClinicalBounds(dangerousOptimization, 'proto_1')).toBe(false);
        expect(systemMonitor.validateClinicalBounds(safeOptimization, 'proto_1')).toBe(true);
    });
});

describe('Quantum Service Manager - Circuit Breaker', () => {
    let serviceManager: QuantumServiceManager;

    beforeEach(() => {
        serviceManager = new QuantumServiceManager();
    });

    it('should default to circuit closed (healthy)', () => {
        expect(serviceManager.isCircuitOpen()).toBe(false);
    });

    it('should register services successfully', () => {
        serviceManager.registerService({
            name: 'test-service',
            endpoint: 'https://test.p31labs.org',
            maxConcurrency: 10,
            healthCheckInterval: 30000,
            timeout: 300000,
            retryAttempts: 3,
            weight: 1
        });

        const stats = serviceManager.getServiceStats();
        expect(stats['test-service']).toBeDefined();
    });
});
